[package]
name = "grim"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "A grimoire for your machines: declarative, cross-platform environment management."

[[bin]]
name = "grim"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.102"
clap = { version = "4.6.1", features = ["derive"] }
grim-apply = { version = "0.0.0", path = "../grim-apply" }
grim-core = { path = "../grim-core" }
